version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.15
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - "discovery.type=single-node"
  # rowstream-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports: 
  #     - 3000:3000
  #     - 8080:8080
  #   volumes:
  #     - .:/usr/src/app      
  #   depends_on:
  #     - "elasticsearch"
  #   environment:
  #     - NODE_ENV=dev
  #   working_dir: /usr/src/app
  #   command: bash -c "./wait-for-it.sh elasticsearch:9200 -t 30 -- npm run dev:debug"
