FROM node:10.24-slim

WORKDIR /usr/src/app

COPY package*.json tsconfig*.json tslint.json ./copyStaticAssets.ts ./wait-for-it.sh ./nodemon.json ./

COPY ./RowStreamSDK ./RowStreamSDK
COPY ./config ./config
COPY ./src ./src

RUN npm install

EXPOSE 3000